version: 2
jobs:
  deploy:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "49:0b:d7:35:63:2d:96:73:bf:03:0a:ba:ed:dc:b5:e6"

      - attach_workspace:
          at: "./"

      - run: ls
      - run: ssh-keyscan zqz.ca >> ~/.ssh/known_hosts
      - run: scp serv zqz@zqz.ca:serv-new
      - run: scp -r db/ "zqz@zqz.ca:"
      - run: ssh zqz@zqz.ca "goose -env production up"
      - run: ssh zqz@zqz.ca "sudo systemctl stop zqz && mv serv serv-old && mv serv-new serv && sudo systemctl start zqz"

  backend:
    docker:
      - image: dylanj/circleci-go:latest

    working_directory: /go/src/github.com/zqz/upl
    steps:
      - checkout
      - restore_cache:
          key: 'go-deps-{{ checksum "Gopkg.lock" }}-{{ arch }}'

      - restore_cache:
          key: 'go-vend-{{ checksum "Gopkg.lock" }}-{{ arch }}'

      - run: dep ensure
      - run: go test -v ./filedb
      - attach_workspace:
          at: ./frontend/build

      - run: go get github.com/elazarl/go-bindata-assetfs/... && go get github.com/jteeuwen/go-bindata/...
      - run: cd frontend/build && go-bindata-assetfs -pkg "server" -prefix "assets" build/... && mv bindata.go ../../server/assets.go
      - run: go build -ldflags='-s' -o bin/serv serv.go

      - save_cache:
          key: 'go-deps-{{ checksum "Gopkg.lock" }}-{{ arch }}'
          paths:
            - /go/pkg/dep
      - save_cache:
          key: 'go-vend-{{ checksum "Gopkg.lock" }}-{{ arch }}'
          paths:
            - vendor

      - persist_to_workspace:
          root: bin
          paths:
            - serv

  frontend:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          key: 'node-{{ checksum "frontend/yarn.lock" }}-{{ arch }}'
      - run: cd frontend && yarn install
      - save_cache:
          key: 'note-{{ checksum "frontend/yarn.lock" }}-{{ arch }}'
          paths:
            - node_modules

      - run: cd frontend && node build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

workflows:
  version: 2
  gogo:
    jobs:
      - deploy:
          requires:
            - frontend
            - backend

      - frontend
      - backend:
          requires:
          - frontend
