name: 'Deploy to Production'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-verison: '1.14.2'
    - run: |
        go build

    - name: 'Copy Build to Server'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "upl"
        target: "/home/zqz/upl-latest"

    - name: 'Extact Artifact'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo systemctl stop zqz
          mv upl upl-previous
          mv upl-latest upl
          sudo systemctl start zqz
